# Generated by Django 5.2.10 on 2026-02-10 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QardHasanContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_text', models.TextField()),
                ('contract_hash', models.CharField(max_length=64)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('BORROWER_SIGNED', 'Borrower signed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FORGIVEN', 'Forgiven')], default='GENERATED', max_length=20)),
                ('borrower_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrow_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='borrow.borrowrequest')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_contracts', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('BORROWER', 'Borrower'), ('SUPPORTER', 'Supporter')], max_length=20)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_consents', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='contracts.qardhasancontract')),
            ],
            options={
                'ordering': ['-consented_at'],
                'unique_together': {('contract', 'user', 'role')},
            },
        ),
    ]
